#! configuration/base.yaml
application:
  port: 8001
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "thanhde.nguyen@shopee.com"
  authorization_token: "2e9fc0d9-7e9f-4562-8fdf-c96b519ae589"